import React, { useState } from "react";
import { Mission, UserProfile } from "../types";
import { 
  Compass, 
  MapPin, 
  Award, 
  ChevronRight, 
  CheckCircle2, 
  Sparkles, 
  Loader2, 
  ShieldCheck, 
  PlayCircle,
  HelpCircle
} from "lucide-react";

interface MissionsControlProps {
  missions: Mission[];
  userProfile: UserProfile | null;
  onCompleteMission: (missionId: string, repReward: number) => void;
  isActionInProgress: boolean;
}

export default function MissionsControl({
  missions,
  userProfile,
  onCompleteMission,
  isActionInProgress
}: MissionsControlProps) {
  if (!userProfile) {
    return <div className="text-center p-8 text-zinc-500 font-mono text-sm">Please sign in to view missions.</div>;
  }
  const [selectedMission, setSelectedMission] = useState<Mission | null>(null);
  const [completingMissionId, setCompletingMissionId] = useState<string | null>(null);

  // Active missions
  const activeMissions = missions.filter(m => m.status === "Active");
  // Checked/Completed ones belongs to profile's completedMissionsList
  const completedMissionsCount = userProfile.completedMissionsList?.length || 0;

  // Calculates percentage progression inside rank based on RP
  const getRankThresholds = (rank: string) => {
    switch (rank) {
      case "Citizen": return { min: 0, max: 100 };
      case "Scout": return { min: 100, max: 300 };
      case "Verifier": return { min: 300, max: 600 };
      case "Inspector": return { min: 600, max: 1000 };
      case "Guardian": return { min: 1000, max: 2000 };
      default: return { min: 2000, max: 5000 }; // Hero cap
    }
  };

  const thresholds = getRankThresholds(userProfile.rank);
  const repInRank = userProfile.reputation - thresholds.min;
  const rankRange = thresholds.max - thresholds.min;
  const rankPercent = Math.min(100, Math.round((repInRank / rankRange) * 100));

  const handleRunVerification = async (mission: Mission) => {
    setCompletingMissionId(mission.id);
    // Simulate slight sensor synchronization lag matching high fidelity AI scans
    setTimeout(() => {
      onCompleteMission(mission.id, mission.repReward);
      setSelectedMission(null);
      setCompletingMissionId(null);
    }, 1800);
  };

  const getMissionIcon = (type: string) => {
    switch (type) {
      case "verify":
        return <ShieldCheck className="h-5 w-5 text-teal-400" />;
      case "confirm_leak":
        return <Compass className="h-5 w-5 text-blue-400" />;
      default:
        return <Award className="h-5 w-5 text-amber-500" />;
    }
  };

  return (
    <div className="max-w-5xl mx-auto px-4 md:px-6 space-y-8 pb-16">
      
      {/* HEADER SECTION */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-[#1f1f21] pb-5">
        <div>
          <h1 className="text-xl font-bold text-zinc-150 tracking-tight flex items-center gap-2">
            <Compass className="h-5.5 w-5.5 text-teal-400" />
            AI Mission Control
          </h1>
          <p className="text-xs text-zinc-400 mt-1">
            Real-time verification objectives proactively generated by municipal cluster analysis.
          </p>
        </div>
        
        {/* Dynamic player stats capsule */}
        <div className="flex items-center gap-3 bg-[#0f0f11] border border-[#1f1f21] p-2.5 rounded-xl">
          <div className="h-8 w-8 rounded-full bg-teal-500/10 border border-teal-500/20 flex items-center justify-center text-teal-400 font-mono text-sm font-bold">
            {userProfile.rank.charAt(0)}
          </div>
          <div>
            <div className="text-xs font-semibold text-zinc-200">{userProfile.displayName}</div>
            <div className="text-[10px] text-zinc-500 font-mono font-medium">Rank: <span className="text-teal-400 font-bold">{userProfile.rank}</span></div>
          </div>
        </div>
      </div>

      {/* COMPACT RANKS PROGRESSION BAR */}
      <div className="glass-panel p-5 rounded-xl border border-[#1f1f21] space-y-4">
        <div className="flex items-center justify-between text-xs font-mono">
          <span className="text-zinc-400">Current Rank: <span className="text-zinc-100 font-bold">{userProfile.rank}</span></span>
          <span className="text-zinc-500">{userProfile.reputation} / {thresholds.max} RP</span>
        </div>
        
        {/* Progress tracks bar */}
        <div className="relative h-2 w-full bg-[#050505] rounded-full overflow-hidden border border-[#1f1f21]">
          <div 
            className="absolute top-0 left-0 h-full bg-gradient-to-r from-teal-400 to-blue-500 rounded-full transition-all duration-500"
            style={{ width: `${rankPercent}%` }}
          />
        </div>

        <div className="flex items-center justify-between text-[10px] text-zinc-500 font-mono">
          <span>{thresholds.min} RP</span>
          <span>{rankPercent}% progress to next tier</span>
          <span>{thresholds.max} RP</span>
        </div>
      </div>

      {/* CORE OBJECTIVES LAYOUT */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        {/* ACTIVE TARGETS LIST (2 Columns) */}
        <div className="md:col-span-2 space-y-4">
          <div className="flex items-center justify-between text-xs font-mono uppercase tracking-wider text-zinc-400">
            <span>Critical Hotspot Objectives ({activeMissions.length})</span>
            <span className="text-[10px]">Earn citizen rank reputation points</span>
          </div>

          <div className="space-y-3">
            {activeMissions.length > 0 ? (
              activeMissions.map((mission) => {
                const isSelected = selectedMission?.id === mission.id;
                const isCompleted = userProfile.completedMissionsList?.includes(mission.id) || false;

                return (
                  <div 
                    key={mission.id}
                    onClick={() => !isCompleted && setSelectedMission(mission)}
                    className={`glass-panel p-4 rounded-xl border transition cursor-pointer select-none space-y-3 relative ${
                      isCompleted 
                        ? "border-emerald-500/10 opacity-70"
                        : isSelected 
                        ? "border-[#2dd4bf]/40 bg-[#1f1f21]/45" 
                        : "border-[#1f1f21] hover:border-[#1f1f21]/80 hover:bg-[#1f1f21]/15"
                    }`}
                  >
                    <div className="flex items-start gap-3">
                      <span className="h-10 w-10 bg-[#050505] border border-[#1f1f21] rounded-lg flex items-center justify-center">
                        {getMissionIcon(mission.type)}
                      </span>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between gap-2">
                          <h4 className="text-sm font-semibold text-zinc-200 truncate">{mission.title}</h4>
                          <div className="flex items-center gap-1.5 font-mono text-[10px] text-zinc-500">
                            <span className="text-teal-400 font-bold">+{mission.repReward} RP</span>
                          </div>
                        </div>
                        <p className="text-xs text-zinc-400 mt-1 lines-clamp-2 leading-relaxed">{mission.description}</p>
                      </div>
                    </div>

                    {/* Expand selection drawer if accepted */}
                    {isSelected && (
                      <div className="pt-4 border-t border-[#1f1f21] flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                        <div className="text-[11px] text-zinc-500 font-mono flex items-center gap-1.5">
                          <MapPin className="h-3.5 w-3.5 text-zinc-650" />
                          Coordinate target: {mission.latitude}, {mission.longitude}
                        </div>
                        <button
                          type="button"
                          onClick={() => handleRunVerification(mission)}
                          disabled={completingMissionId === mission.id}
                          className="bg-teal-500 hover:bg-teal-450 text-[#050505] font-semibold text-xs px-4.5 py-2 rounded-lg shadow-lg flex items-center justify-center gap-2 cursor-pointer border border-teal-450 transition-all ml-auto max-sm:w-full"
                        >
                          {completingMissionId === mission.id ? (
                            <>
                              <Loader2 className="h-4 w-4 animate-spin text-[#050505]" />
                              Syncing Field Sensors...
                            </>
                          ) : (
                            <>
                              <PlayCircle className="h-4 w-4" />
                              Approve Verification Checklist
                            </>
                          )}
                        </button>
                      </div>
                    )}
                  </div>
                );
              })
            ) : (
              <div className="p-8 text-center text-zinc-500 bg-[#0f0f11]/25 border border-[#1f1f21] rounded-xl font-mono text-xs">
                All community systems secure. AI has resolved active mission bottlenecks!
              </div>
            )}
          </div>
        </div>

        {/* MISSION HUD CONTROL SPECIFICATION (1 Column) */}
        <div className="space-y-5">
          <div className="text-xs font-mono uppercase tracking-wider text-zinc-400">Mission Health Stats</div>
          
          {/* Progress overview */}
          <div className="glass-panel p-4.5 rounded-xl border border-[#1f1f21] space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs text-zinc-400">Total Cleared</span>
              <span className="text-sm font-semibold font-mono text-zinc-150">{completedMissionsCount}</span>
            </div>
            
            <div className="flex items-center justify-between">
              <span className="text-xs text-zinc-400">Rank Standing</span>
              <span className="text-xs font-mono text-teal-400 font-bold">{userProfile.rank}</span>
            </div>

            <div className="border-t border-[#1f1f21] pt-4 text-xs space-y-2 leading-relaxed">
              <div className="font-semibold text-zinc-300 flex items-center gap-1">
                <Sparkles className="h-3.5 w-3.5 text-teal-400" />
                How Missions Work:
              </div>
              <p className="text-zinc-500 text-[11px]">
                The Community Artificial Intelligence surveys open incident density grids. It flags critical points requiring field verification, and packages them into reward-bearing citizen missions.
              </p>
              <p className="text-zinc-500 text-[11px]">
                Navigate safely to coordinate areas, audit physical reports, and submit confirmation logs to progress your municipal rank.
              </p>
            </div>
          </div>
        </div>

      </div>

    </div>
  );
}
